stages:
  proprocess:
    cmd: python .\src\preprocess.py
    deps:
    - .\data\raw\
    - .\src\preprocess.py
    outs:
    - .\data\preprocess\
  model_building:
    cmd: python .\src\train.py
    deps:
    - .\data\preprocess\
    - .\src\train.py
    outs:
    - model.pkl
  evaluate:
    cmd: python .\src\evaluate.py
    deps:
    - .\src\evaluate.py
    - model.pk
    outs:
    - accuracy
